package tv.abema.flagfit

import tv.abema.flagfit.annotation.BooleanFlag
import tv.abema.flagfit.annotation.VariationFlag

/**
 * A pre-resolved boolean flag which can be evaluated without reflection.
 *
 * Instances are created by [Flagfit.resolveBooleanFlag] and are mainly used by
 * code generated by the flagfit-ksp processor.
 */
class BooleanFlagResolution internal constructor(
  val booleanFlag: BooleanFlag,
  val flagSource: FlagSource?,
  val env: Map<String, Any>,
) {
  fun get(): Boolean {
    return when (flagSource) {
      null -> booleanFlag.defaultValue
      is BlockingBooleanFlagSource -> flagSource.get(
        booleanFlag.key,
        booleanFlag.defaultValue,
        env
      )

      else -> throw IllegalArgumentException("FlagSource should be BlockingFlagSource")
    }
  }

  suspend fun fetch(): Boolean {
    return when (flagSource) {
      null -> booleanFlag.defaultValue
      is SuspendableBooleanFlagSource -> flagSource.fetch(
        booleanFlag.key,
        booleanFlag.defaultValue,
        env
      )

      else -> throw IllegalArgumentException("FlagSource should be SuspendableFlagSource")
    }
  }
}

/**
 * A pre-resolved variation flag which can be evaluated without reflection.
 *
 * Instances are created by [Flagfit.resolveVariationFlag] and are mainly used by
 * code generated by the flagfit-ksp processor.
 */
class VariationFlagResolution<T : Any> internal constructor(
  val variationFlag: VariationFlag,
  val variationAdapter: VariationAdapterInterface<T>,
  val flagSource: FlagSource?,
  val env: Map<String, Any>,
) {
  fun get(): T {
    return when (flagSource) {
      null -> variationAdapter.variationOf(variationFlag.defaultValue)
      is BlockingStringFlagSource -> variationAdapter.variationOf(
        flagSource.get(variationFlag.key, variationFlag.defaultValue, env)
      )

      else -> throw IllegalArgumentException("FlagSource should be BlockingFlagSource")
    }
  }

  suspend fun fetch(): T {
    return when (flagSource) {
      null -> variationAdapter.variationOf(variationFlag.defaultValue)
      is SuspendableStringFlagSource -> variationAdapter.variationOf(
        flagSource.fetch(variationFlag.key, variationFlag.defaultValue, env)
      )

      else -> throw IllegalArgumentException("FlagSource should be SuspendableFlagSource")
    }
  }
}
