apply plugin: 'java-library'
apply plugin: 'kotlin'

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  implementation "com.google.devtools.ksp:symbol-processing-api:$kspVersion"
  implementation 'com.squareup:kotlinpoet-ksp:1.18.1'
  testImplementation 'junit:junit:4.13.2'
  testImplementation project(':flagfit')
  testImplementation project(':flagfit-flagtype')
  testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0'
  testImplementation 'dev.zacsweers.kctfork:ksp:0.5.1'
}

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}
