name: Create Issues from SARIF

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * 1' # Runs every Monday

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # ratchet:actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: lint
        run: ./gradlew :sample-android:lintDebug

      - name: Create issues from SARIF files
        env:
          HEAD_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          kotlin scripts/maintain-flagfit-expiration-issue.main.kts
